credentials:
  client_id: ""
  client_secret: ""
  username: ""
  password: ""
  user_agent: ""

bot:
  trigger_phrases:
    - " Hello "
  reply_text: "I am a bot"

subs:
  blacklist:
    - "cricket"
  whitelist:
    - "pics"
